### PR TITLE
Fix summernote codeview

### LINKED ISSUE #1467: Summernote code editor not working like expected
Summernote requires code view to be closed before the changes is put to text area. For example at the Xtheme-editor open code view -> edit -> save -> changes not saved.

Maybe we should start with help texts in case the issue is too deep in Summernote.

### PR DESCRIPTION
**Pull request by maximlion**
The issue is with summernote itself, this is a simple workaround. Summernote content can now be saved from codeview.

This fixes #1467

### CODE REVIEW

File: shuup/admin/static_src/base/js/editor.js [hunk 1]
```diff
@@ -64,6 +64,12 @@ function activateEditor($editor, attrs = {}) {
     $editor.parent().find(".note-editable").on("drop", (event) => {
         cancelEvent(event);
     });
+
+    $(".note-codable").on("blur", function() {
```
Comment (chessbr) [inline shuup/admin/static_src/base/js/editor.js]: I really didn't get what are you trying to achieve. If you want to invoke some function in summernote instance, you can already use `$editor` here.. and I am pretty sure you can access the textarea using `$editor.parent().find("textarea");` Please, take a look at the existing code.

File: shuup/gdpr/static_src/gdpr.js [hunk 2]
```diff
@@ -40,7 +40,7 @@
             url: $("#consent-form").attr("action"),
             type: 'POST',
             data: data,
-            success: function() {
+            complete: function() {
```
Comment (chessbr) [inline shuup/gdpr/static_src/gdpr.js]: why complete? if the request fails, that things shouldn't be removed

File: shuup/gdpr/static_src/gdpr.js [hunk 3]
```diff
@@ -55,4 +55,13 @@
     $("#agree-btn").click(() => {
         saveConsent();
     });
+    }
+
+    if(typeof jQuery === 'undefined'){
+        document.getElementsByClassName("gdpr-consent-warn-bar")[0].hidden=true;
```
Comment (chessbr) [inline shuup/gdpr/static_src/gdpr.js]: add space `hidden = true;`

File: shuup/xtheme/templates/shuup/xtheme/editor.jinja [hunk 4]
```diff
@@ -62,7 +62,7 @@
                 },
                 callbacks: {
                     onBlur: function() {
-                        $(this).parent().find("textarea.hidden").val($(this).summernote('code'));
+                        $(this).parent().find("textarea.hidden").val($(this).summernote('code'));
```
Comment (chessbr) [inline shuup/xtheme/templates/shuup/xtheme/editor.jinja]: remove trailing space

File: shuup/xtheme/templates/shuup/xtheme/editor.jinja [hunk 5]
```diff
@@ -84,6 +84,12 @@
                 cancelEvent(event);
             });
         })
+
+        $('.note-codable').on('blur', function() {
```
Comment (chessbr) [inline shuup/xtheme/templates/shuup/xtheme/editor.jinja]: same as the first comment

File: shuup/gdpr/static_src/gdpr.js (hunk 2 above)
Comment (maximlion) [reply shuup/gdpr/static_src/gdpr.js]: "gdpr consent can be accepted on any page where jquery is imported(before it was only available upon successful request completion)," for instance, 404 page wasn't failing just because it didn't have jquery imported, when jquery was imported it would return an "error" 404 request instead of a successful 302 or 200. This was blocking the code execution for removing GDPR boxes.

Comment (chessbr) [reply shuup/gdpr/static_src/gdpr.js]: IMO, you should warn user when an error occurs and then remove the preferences or something.. this is hiding the actual error

File: shuup/admin/static_src/base/js/editor.js [hunk 6]
```diff
@@ -64,6 +64,12 @@ function activateEditor($editor, attrs = {}) {
     $editor.parent().find(".note-editable").on("drop", (event) => {
         cancelEvent(event);
     });
+
+    $editor.parent().find(".note-codable").on("blur", function() {
+        $(this).closest(".note-editor").siblings("textarea").val(
```
Comment (chessbr) [inline shuup/admin/static_src/base/js/editor.js]: textarea can be reached like this: `const textarea = $editor.parent().find("textarea");`

File: shuup/gdpr/static_src/gdpr.js [hunk 7]
```diff
@@ -55,4 +58,13 @@
     $("#agree-btn").click(() => {
         saveConsent();
     });
+    }
+
+    if(typeof jQuery === "undefined"){
```
Comment (chessbr) [inline shuup/gdpr/static_src/gdpr.js]: format this block correctly
image

File: shuup/gdpr/static_src/gdpr.js [hunk 8]
```diff
@@ -44,6 +44,9 @@
                 $(".gdpr-consent-warn-bar").remove();
                 $(".gdpr-consent-preferences").remove(); // Remove GDPR divs and their content upon successful completion
                 $("body").removeClass("body-noscroll");
+            },
+            error: function (jqXHR, textStatus, errorThrown) {
+                window.alert("An error hasoccurred while saving the consent, please try again.");
```
Comment (chessbr) [inline shuup/gdpr/static_src/gdpr.js]: this this message
